# Generated by Django 4.0.5 on 2022-06-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_options_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created', '-created']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='post_url',
        ),
    ]
